#!/bin/bash  
 
abs="$(dirname $(readlink -f "$0"))"
eval "$(cat ${abs}/activity.conf)"

wnd_focus=$(xdotool getwindowfocus)
wnd_title=$(xprop -id $wnd_focus WM_NAME)
wnd_class=$(xprop -id $wnd_focus WM_CLASS)
lookfor='"(.*)"'
 
if [[ "$wnd_class" =~ $lookfor ]]; then
  wnd_class=${BASH_REMATCH[1]}
fi

if [[ "$wnd_title" =~ $lookfor ]]; then
  wnd_title=${BASH_REMATCH[1]}
fi

for a in ${activity[@]}; do
  activity=$(echo $a | cut -d\: -f1)
  class=$(echo $a | cut -d\: -f2)
  name=$(echo $a | cut -d\: -f3)
  if [[ "$wnd_title" =~ $name ]]; then
    echo $activity
    exit 0
  fi
  if [[ "$wnd_class" =~ $class ]]; then
    echo ${activity}
    exit 0
  fi
done
echo other
exit 0
