#!/bin/bash
abs="$(dirname $(readlink -f "$0"))"
eval "$(cat ${abs}/keyboard.conf)"
if [ ! -z $keydevice ]; then
  pressed="$(echo $(sudo timeout 60 cat ${keydevice}))"
  count=$(expr "$(echo ${pressed} | wc -c - | cut -d\  -f1)" / 53)
  apm=$(expr ${count} \* 1)
  echo $apm
  exit 0
else
  if [ ! -z $keyfile ]; then 
    exit 1
  else
    exit -1
  fi
fi
