#!/bin/bash
eval "$(cat ./config)"
if [ ! -z $keydevice ]; then
  echo "Reading bytes from ${keydevice}"
  i=0
  while true; do
    pressed="$(echo $(sudo timeout 10 cat ${keydevice}))"
    count=$(expr "$(echo ${pressed} | wc -c - | cut -d\  -f1)" / 53)
    echo "|${count}|"
    apm=$(expr ${count} \* 6)
    echo "APM ≅ ${apm}"
    echo "${i} ${apm}" >> /tmp/apm
    i=$(expr "$i" + 10)
  done
else
  if [ ! -z $keyfile ]; then 
    echo "Reading decoded key presses from ${keyfile} is not implemented."
  fi
fi
